### ISSUE TITLE
Resourcekey vs Key bug

### ISSUE THREAD

**Issue by garfieldos** [damienbod/Angular2LocalizationAspNetCore#7]
How should I understand Key and resourceKey on tthe localizationrecords db?

#My case: 

i want to add Two records:

```SQL
insert into dbo.localizationrecords
([Key],localizationculture,resourcekey,text,updatedTimestamp)
values  ('bank transfer','en','Iwencik.Host.Views.Registration.DetailsIwencik.Host','Bank transfer',getdate())
, ('bank transfer','en','Iwencik.Host.Controllers.RegistrationController','Bank transfer',getdate()))
```
Both records has the same key but another resourceKey. I would assume, that there is posibility to add Two records with this same key and another resorce key, but when i try to add this records i get duplicate key constraint exception:

```SQL
Msg 2627, Level 14, State 1, Line 49
Violation of UNIQUE KEY constraint 'AK_LocalizationRecords_Key_LocalizationCulture'. Cannot insert duplicate key in object 'dbo.LocalizationRecords'. The duplicate key value is (bank transfer, en).
The statement has been terminated.
```
Is it bug or my bad understanding of using this model?

**Comment by damienbod** [comment]
Hi @garfieldos I use the Key and the localizationculture as a constraint, because I assumed that it makes no sense to repeat this translation, the bank transfer is the same, just used form 2 different controllers, views. 

I was thinking this would make more sense as a shared resource. 

May it would be better if I used the resourcekey also in the constraint, then the user of the package can decide.

If you want, I can add this, I also need to update to 1.1.

Opinion? 

Greetings Damien

**Comment by garfieldos** [comment]
One key for all resource would be good, if there will be some possibility to reach this translation withot resourcekey context (without view/controller context).  
Now we are using Localizer object with view/controller context and in all that contextes it should be a possibility of using this same translation keys (because their meaning could differ across different contextes).

I think, that it should be composite key on columns: Key and ResourceKey (of course sense of column name: "key" will be lost after this change)

**Comment by damienbod** [comment]
@garfieldos makes sense, I'll make the constraint using all 3 properties. The key still makes sense for me, as this is the key without the resource.

Will update this ASAP. (also only with .NET 1.1) I want to move on from 1.0. Is this ok, or do you require the fix for .NET Core 1.0?

Greetings Damien

**Comment by garfieldos** [comment]
1.1 will be ok for me.
Thx

**Comment by damienbod** [comment]
@garfieldos 
Updated NuGet:
https://www.nuget.org/packages/Localization.SqlLocalizer/1.0.4

Code:
https://github.com/damienbod/AspNet5Localization/tree/master/AspNet5Localization/src/Localization.SqlLocalizer

**Comment by garfieldos** [comment]
Thx a lot!
